### ISSUE TITLE
Limit user input for text

### ISSUE THREAD

**Issue by durinthal** [r-anime/flairsite#2]
This is mostly to avoid people putting whatever they want.

How I envision it:

* User selects icon
* User select list site (MAL/Anilist/AniDB/etc.)
* User enters account name

The site selected determines a prefix URL that's not editable, e.g. `https://anilist.co/user/`

To go an extra step further we could try to validate that an account by that name exists on the site selected.

**Comment by Badspler** [comment]
https://github.com/r-anime/flairsite/blob/master/flair/flairparsing.py#L173

Validates user name to only allow what flair-tracker's would allow for their username (or in Kitsu.io case, the URL to the profile). 

In addition allows slash ( / ). This is such that MAL/Anilist have a suffix to the url that takes you from profile to anime-watching list. Will allow the user to set it, if the combined character length isn't above 20 characters. 

Eg: 'badspler' vs 'badspler/animelist' which would result in either: 

https://anilist.co/user/badspler
https://anilist.co/user/badspler/animelist
