### ISSUE TITLE
Scrollbar fixes in set flair

### ISSUE THREAD

**Issue by bernasx** [r-anime/flairsite#7]
As seen in the image below, the scrollbar gets close to the right side column which ruins the look of the page when the cards are right beside it. There should be a separation between columns.

![31_05_21_00_34 chrome_DKlNQSzJuy](https://user-images.githubusercontent.com/38398866/120123654-f2ac2800-c1a7-11eb-9e61-42c373101524.png)

Additionally, scroll bars should be hidden when not focused.

**Comment by bernasx** [comment]
Potentially fixed in #13 awaiting review to close.

**Comment by Badspler** [comment]
Resolves issue described.
